panda3d/panda3d

panda/src/grutil/meshDrawer.cxx

Direction vector is computed as stop - start, but the position
in the loop is computed from stop as base, instead of from start;
this is changed to start as the base (and then offset must be added).
Multiplication of non-normalized direction vector with its length
yields square of the expected current step inside the loop;
this is changed to use the normalized direction vector.

Fix MeshDrawer::stream

---

direct/src/actor/Actor.py

Revert "Patch by cfsworks: actor: On removePart, clean up the part's commonBundleHandle."
This reverts commit a4563fb342715bccd9a63aa320395f13abaace46.
commonBundleHandle is not holding bundle for this part only. When
two or more parts shares or have similar bundles - their bundles
are merged. In these cases it is not correct to remove
the commonBundleHandle for this parts.

Fix broken animations when multipart actor have completely overlapping parts

---

doc/man/pview.1
panda/src/testbed/pview.cxx

In my workflow, I always need lighting (so textures show up) and prefer to use p3tinydisplay for faster startup.  This patch allows passing options to enable lighting and select the display.

Add -L (lighting) and -d <display> options to pview

---

panda/src/gobj/texture.cxx

I saw a reference to this on irc the other day and then ran into it myself once I loaded up some MakeHuman-generated models.
-- originally the code had an explicit check for a missing alpha channel, that went away in 22120524a2f9a1f9330cdfa2b35bbcdf15d721d4
-- example is:
```
<Texture> tongue01:diffuse.002 {
"./tex/tongue01_diffuse.png"
<Scalar> envtype { MODULATE }
<Scalar> minfilter { LINEAR_MIPMAP_LINEAR }
<Scalar> magfilter { LINEAR_MIPMAP_LINEAR }
<Scalar> wrap { REPEAT }
<Scalar> alpha-file { "./tex/tongue01_diffuse.png" }
<Scalar> alpha-file-channel { 4 }
}
```
for an image w/o alpha:
```
file ./tex/tongue01_diffuse.png
./tex/tongue01_diffuse.png: PNG image data, 1024 x 1024, 8-bit/color RGB, non-interlaced
```

Fix a rash of asserts from PNMImage::get_alpha_val

---

panda/src/rocket/rocketInputHandler.cxx

Some ASCII chars fell through and generate no events when modifier keys are held down.  E.g. pressing "Ctrl+\" emits neither a 'keydown' nor a 'textinput' event for libRocket.  
libRocket calls several punctuation keys "OEM" in its KeyIdentifier enum, so I assume those were overlooked.  This patch fills those in from Panda's side, assuming a US English keyboard, like libRocket's comments say.  Better that than losing the events entirely...?

Make more keys available to libRocket event handlers

---

panda/src/pnmimage/pnmImage.cxx
panda/src/pnmimage/pnmImage.h

Ought to be straightforward, except perhaps the naming of the methods.  Feel free to change them.
(I fought so hard thinking blend_sub_image() or blend() had some bug, and was making all sorts of elaborate fixes and extensions for that, but finally realized it was all my fault, hence these methods :-p.)

Add PNMImage premultiply/unpremultiply methods.

---

makepanda/makepanda.py

PackageMaker isn't as easy to find and download anymore, whatever versions online that are available for download sometimes install the program into Applications/ folder or Developer/Tools/ with the name PackageMaker.app.
This pull request adds two new file paths to check for PackageMaker.app.

makepanda.py: added more refs for PackageMaker

---

direct/src/distributed/GridChild.py

This import is nonexistent and has no calls to it. The only purpose it serves right now is causing an ImportError :P.

Removed a nonexistent import from GridChild

---

direct/src/p3d/Packager.py
direct/src/p3d/ppackage.py

-- Provide addExtension(...) method to augment particular kinds of files, allowing them to be packaged
-- Track the count of files, by extension, silently ignored by dir(), and log this

Handle packaging user filetypes more extensibly

---

panda/src/rocket/rocketInputHandler.cxx

On Linux (at least), a key event is accompanied with a mouse position
event.  If a libRocket UI is listening to e.g. "mouseover" events,
then any keypress will first appear to be a mouse movement, tripping
up code that tries to handle focus with both keyboard and mouse
support.
This change merely dispatches key events before any mouse events to
avoid this problem.

Send libRocket key events before mouse events

---

pandatool/src/assimp/assimpLoader.cxx
pandatool/src/assimp/assimpLoader.h

Here's a first attempt at skinned meshes via Assimp. Some things to note:
* I haven't checked for new memory leaks
* The use of const char* as a hash key seems kind of ugly, but it also seems like the simplest approach.
* Some NULL checks might be good. An aiBone should have a matching aiNode, but it might be good to protect ourselves if Assimp misbehaves.
* The tbtable->set_rows() could be optimized to leave out non-animated verts
GitHub doesn't like archive files, so I've uploaded one to Dropbox: https://dl.dropboxusercontent.com/u/3431679/skel_mesh.zip
Inside you'll find:
* animbox.blend -- The original blend file
* animbox.dae -- The COLLADA file exported from Blender using the Better COLLADA plugin
* main.py -- The script to test with

Assimp: Add support for skinned meshes (no animations yet).

---

panda/src/cocoadisplay/cocoaGraphicsWindow.mm
panda/src/cocoadisplay/cocoaPandaView.mm
panda/src/osxdisplay/osxGraphicsWindow.mm
samples/mouse-modes/main.py

Note: it seems that using #set_pointer() will result in
a long delay before an absolute mouse position is updated,
even though deltas are reported.
Thus, in CocoaPandaView, the mouse deltas are sent for both
relative and confined modes, so client code (e.g. the "mouse
modes" demo) will be able to recenter the mouse without
choppy movement.

Implement confined mouse mode for OS X.

---

pandatool/src/assimp/assimpLoader.cxx
pandatool/src/assimp/assimpLoader.h

[skel_anim.zip](https://github.com/panda3d/panda3d/files/76065/skel_anim.zip) contains:
* animbox.blend - Original blend file
* animbox.dae - COLLADA file exported from Blender via Godot's Better COLLADA addon
* main.py - Script used to test the changes
Known issues:
* A model will fail to load if all channels in an animation do not have the same number of keyframes
* Any animations on the skeleton/armature itself are not converted since it is not a bone (and thus not in the bonemap)
* Animations from COLLADA files exported by Godot's Better COLLADA addon do not have a name
* Not sure if this is an issue with the addon or with Assimp
* For the time being, all AnimBundleNodes are given the name "anim" since the animations mName is empty

Assimp: Add initial support for skeletal mesh animations

---

panda/src/linmath/lpoint3_src.h
panda/src/linmath/lpoint4_src.I
panda/src/linmath/lpoint4_src.h
panda/src/linmath/lvecBase3_src.h
panda/src/linmath/lvecBase4_src.h
panda/src/linmath/lvector3_src.h
panda/src/linmath/lvector4_src.I
panda/src/linmath/lvector4_src.h

This pull requests fixes certain swizzle masks on the builtin vector types, namely those derived from LVecBase3 and LVecBase4. 
It ensures that calling get_xy() on a LPoint3f for example returns an LPoint2f, and not LVecBase3f.

Fix swizzle masks on vector types

---

panda/src/glstuff/glGraphicsStateGuardian_src.cxx

This pr fixes a typo in glGraphicsStateGuardian, preventing text and sprites to be rendered with their color only.

Fix typo in glGraphicsStateGuardian

---

panda/src/gobj/texturePeeker.cxx

This PR adds more formats to the TexturePeeker, and more important, emits an error in case the format is currently not supported so the user knows whats going wrong (Except getting errors because `Texture::peek()` returns `None`)

Add more formats to TexturePeeker, emit error if format is not supported

---

panda/src/gobj/texturePeeker.I
panda/src/gobj/texturePeeker.cxx
panda/src/gobj/texturePeeker.h

This adds the `calc_bilinear_point` method to the TexturePeeker, so bilinear lookups can be performed. This is similar to `PfmFile::calc_bilinear_point()`.

Add bilinear filtering to TexturePeeker

---

panda/src/glstuff/glShaderContext_src.cxx

This PR adds support for the imageCubeArray GLSL type (GL_IMAGE_CUBE_MAP_ARRAY).
Also, the _EXT suffix is removed from the GL_IMAGE types.

Support for imageCubeArray, remove _EXT suffix

---

panda/src/express/virtualFileMountRamdisk.cxx

When writing multiple times per second to a file on a VirtualFileMountRamdisk, the file is not cached properly. This is due to the timestamp resolution (which only captures seconds).
This PR fixes the issue, by ensuring that the modified timestamp is always greater than the original timestamp.
This might lead to timestamps from the future, however this is not a concern.
The proper solution would be to switch to a higher precision timer, but for now, this fixes the issue.

Work around timestamp precision in ramdisks

---

direct/src/p3d/panda3d.pdef

See PEP3108 for more details on stdlib differences. This has only been tested on Python 3.

Handle Python 2 vs Python 3 stdlib differences when building the morepy package

---

samples/shader-terrain/main.py

This adds `gl-coordinate-system default` to the shader terrain mesh sample to make the shader terrain works as expected. Otherwise the LOD is computed in a wrong way.

Fix missing coordinate system in sample

---

direct/src/fsm/FSM.py

filter(request, args) can return None, and in that case an error will be thrown.
The list() procedure is unnecessary, since if the filter returns a string, it will be wrapped into a tuple anyways.

Fix error "TypeError: 'NoneType' object is not iterable"

---

direct/src/interval/MetaInterval.py

tuple and list shouldn't be used as parameter names. With the new Python 2.7.11 these break Sequences altogether.

Fix several Sequence crashes

---

panda/src/grutil/shaderTerrainMesh.I
panda/src/grutil/shaderTerrainMesh.cxx
panda/src/grutil/shaderTerrainMesh.h
samples/shader-terrain/main.py

This patch allows setting the heightfield handle directly on the shader terrain mesh, instead of specifying a filename.
This makes the terrain more flexible, and also avoids having to copy the heightfield each time it changed.
The property `heightfield_filename` has been replaced with `heightfield`

Support for setting a heightfield handle directly on the ShaderTerrainMesh

---

panda/src/glstuff/glGraphicsStateGuardian_src.cxx
panda/src/gobj/texture.cxx
panda/src/gobj/texture.h

This adds Texture::F_r16i, to be used with T_unsigned_short and T_short. Internally GL_R16I and GL_R16UI is used.

Support for R16I and R16UI

---

direct/src/distributed/DistributedObjectBase.py

This property is not used and causes problems on the latest build.

Remove useless "children" property of DistributedObjectBase

---

direct/src/p3d/SeqValue.py

Python 3 uses `__lt__` and `__gt__` instead of `__cmp__`.

Fix pmerge to work with Python 3

---

direct/src/distributed/DistributedObjectGlobalUD.py

This code has references to the VR Studio game called Pirates Online of the Caribbean. Unfortunately, this code is not compatible with the current server repository. Calling execCommand throws an error.
I have replaced the proprietary code with a notify call instead.

Remove PiratesMagicWordManager VR Studio code reference

---

panda/src/glstuff/glShaderContext_src.cxx
panda/src/glstuff/glmisc_src.cxx
panda/src/glstuff/glmisc_src.h

Usually image inputs are only used as writeonly variables, this pr adds a new prc option `gl-force-image-bindings-writeonly` which forces all those bindings to be writeonly.
This is equivalent to passing `read=False, write=True` on all `set_shader_input` calls for image bindings, and just a more convenient way.

Add prc variable to force image bindings as writeonly

---

panda/src/parametrics/parametricCurveCollection.h

This fixes typo of include guard in parametricCurveCollection.h file.
I found compile error when I included both nodePathCollection.h file and parametricCurveCollection.h file.

Fix typo of include guard.

---

panda/src/device/evdevInputDevice.cxx
panda/src/device/inputDevice.h

Changes to make the buttons of a device not only usable using events but also the get_button* functions from the python side. Previously button states weren't correctly set by the evdevInputDevice class and the button states enum was not accessible at al from python.

Fixes for device button handling

---

direct/src/showbase/Messenger.py

If one needs to use find() or findAll() not for debugging purposes (like for getting the function or arguments for some binding), then the print functions in these methods are really unwelcome. find() is the only nice way to get this info (other then de-name-mangling __callbacks)

Remove print() from Messenger.find() and Messenger.findAll()

---

panda/src/pgraph/renderAttrib.cxx
panda/src/pgraph/renderState.cxx
panda/src/pgraph/transformState.cxx

In non-debug, the codes do not run and the deleted item is not removed.
So, a crash happens when hash map is cleared.

Fix assert macros that cause a crash in non-debug

---

makepanda/makepandacore.py

Windows 10 SDK binary files are installed in versioned folder from Creator Update (10.0.15063.0)
This fixes the issue that 'rc.exe' file cannot be found.

Add additional Windows SDK path to enviroment variable

---

dtool/src/dtoolutil/load_dso.cxx

Hello. I found the issue that graphics pipe DLL (ex, libpandagl.dll) cannot be loaded when unicode characters exist in the path of the DLL. This RP fixes this issue.
I tested if the issue is resolved on the following systems:
- Windows 10 English version (cp437), C++ & Python
- Windows 10 Korean version (cp949), C++ & Python

Fix failure to load DLL with unicode path

---

panda/src/pnmimagetypes/config_pnmimagetypes.cxx
panda/src/pnmimagetypes/config_pnmimagetypes.h
panda/src/pnmimagetypes/pnmFileTypePNG.cxx

This PR adds a _png-compression-level_ PRC variable to Panda. It allows to choose the compression level for writing out PNG images. Valid values are 0 (no compression), or 1 (best speed) to 9 (best compression). The default value is 6 and has been 6 when used in conjunction with libpng+zlib. PNG compression is lossless.
The resulting file size for PNG files could be optimized further by choosing "filters" intelligently as described on http://www.libpng.org/pub/png/book/chapter09.html and in http://www.libpng.org/pub/png/book/LCH-png-chapter.pdf . However, this is out of scope here and several programs like PNGCRUSH and OptiPNG exist that aim to accomplish this task.
For the future, a nice-to-have would be to be able to disable chroma subsampling for writing out JPEG images.

Introduce png-compression-level PRC variable

---

panda/src/event/eventHandler.cxx
panda/src/event/eventHandler.h

Hello. This PR adds `has_hook` functions taking function pointer or callback data in EventHandler.
I needed the functions to check a specific hook, but those did not exist. So, I added them.

Add has_hook functions taking additional parameter

---

panda/src/collide/collisionBox.I
panda/src/pgraph/clipPlaneAttrib.cxx
panda/src/pgraph/lightAttrib.cxx

Noticed a typo in the CollisionBox docs that duplicated the word 'of'. Ran grep on the rest of the repo and fixed it in the other locations, too.

Fix 'of of' doc typos

---

panda/src/audio/audioManager.h
panda/src/audiotraits/fmodAudioManager.cxx
panda/src/audiotraits/fmodAudioManager.h
panda/src/audiotraits/fmodAudioSound.cxx
panda/src/audiotraits/openalAudioManager.cxx
panda/src/audiotraits/openalAudioManager.h
panda/src/audiotraits/openalAudioSound.cxx

The semantics of distance factor is now same for both OpenAL and Fmod.
The value is given in units per meter, and the default is 1.0.
This means that Panda units are understood to be meters by default.
For example, for feet one would have to set this value to 3.28.

Consolidate distance factor for 3D audio

---

panda/src/pgraph/shaderInput.h

Hello, I found a compilation error that occurs when building without Python on the following line:
https://github.com/panda3d/panda3d/blob/075cb14cbbb004fb167632b630d35e8d03e92e03/panda/src/pgraph/shaderInput.h#L142
This PR fixes it.

Fix compile error by missing header file

---

makepanda/makepanda.py

This PR fixes building Panda3D with HarfBuzz under MSVC.
Note: Panda expects that HarfBuzz has been compiled with Freetype (`-DHB_HAVE_FREETYPE=ON` for CMake), otherwise `hb-ft.h` will not be available.
Build error message before this fix:
`[ 33%] Building C++ object built/tmp/p3text_composite1.obj
p3text_composite1.cxx
c:\build-panda\panda3d-master\panda\src\text\dynamicTextFont.cxx(48): fatal erro
r C1083: Cannot open include file: 'hb-ft.h': No such file or directory
Storing dependency cache.
Elapsed Time: 13 min 6 sec
The following command returned a non-zero value: cl /favor:blend /wd4996 /wd4275
/wd4273 /DWINVER=0x501 /Zc:threadSafeInit- /Fobuilt/tmp/p3text_composite1.obj /
nologo /c /Ipanda/src/text /Ibuilt/tmp /Ibuilt/include /Ithirdparty/win-python3.
6-x64/include …

makepanda: fix building with HarfBuzz under MSVC

---

dtool/src/interrogatedb/py_wrappers.cxx
dtool/src/interrogatedb/py_wrappers.h

Hello, I added `HAVE_PYTHON` macro to `py_wrappers` source and header files to fix errors occur when building without python library.

Add HAVE_PYTHON macro to build without python

---

direct/src/showbase/Loader.py

- Clean up the _loader after we clean up the requests,
not before that

Loader: Fixed crash when canceling async loading of model

---

panda/src/display/graphicsEngine.cxx

Hello, I found a crash by end iterator that is returned when the removed window is not in `_new_windows`. This PR fixes the crash.

Fix crash by end iterator while closing a window

---

panda/src/bullet/bulletGhostNode.cxx

- Fixed deadlock when loading ghost nodes from collision solids and
have non-identity scale applied.

bullet: Fixed deadlock when loading from collision solids

---

direct/src/interval/MetaInterval.py
direct/src/showbase/ObjectPool.py

- Removed undeclared variable `rogerroger` in MetaInterval.
- It appears that the intended functionality of ObjectPool.containerLenStr was to print out the keys of `_len2obj`.  I've implemented this by looping through lengths.

direct: Fix some NameErrors

---

panda/src/audiotraits/config_openalAudio.cxx
panda/src/audiotraits/config_openalAudio.h
panda/src/audiotraits/openalAudioManager.cxx
panda/src/audiotraits/openalAudioManager.h
panda/src/audiotraits/openalAudioSound.I
panda/src/audiotraits/openalAudioSound.cxx
panda/src/audiotraits/openalAudioSound.h

The real meat and potatoes of this changeset is in the first two commits; those address some assumptions that the OpenAL plugin makes about the OpenAL implementation's behavior (which are, evidently, guaranteed with OpenAL Soft, but not so much on Apple OpenAL).
The remaining 4 commits are just making the OpenAL code much more robust, including adding more assertions to verify state and generally making the intended behavior of the code much clearer.
Since these are pretty substantial changes, I'm submitting them as a PR so the following can be heavily scrutinized:
* I used `assert` instead of the `nassert` variants, for consistency with the one `assert` that was already there. What's the engine core's standards on asserts? Should these be `nassertv` etc.?
* How did I do with my PRC …

Clean up OpenAL (and fix some Apple bugs)

---

panda/src/pgraphnodes/sceneGraphAnalyzer.I
panda/src/pgraphnodes/sceneGraphAnalyzer.cxx
panda/src/pgraphnodes/sceneGraphAnalyzer.h

- Corrected the type of texture bytes variable as it is possible
to wrap it around

pgraphnodes: Fixed the type of texture bytes in sceneGraphAnalyzer

---

direct/src/distributed/ConnectionRepository.py
direct/src/distributed/ServerRepository.py

In ac8417ffdf0f253d8c2653b9a27becee1833778c type checks were changed to use Python's inspect module in order to safeguard against any Python 2 and Python 3 differences. However, an inequality check was replaced with an incorrect equality check.
This means that bonafide classes are regarded as non-classes and vice-versa, and as such DC files can no longer load, raising a "Symbol ClassName is not a class name." exception on load.
This commit resolves that issue.

Fix DC file reading regression caused by ac8417f

---

panda/src/event/asyncTaskChain.cxx

I found a crash happens when I remove non-owned tasks.
The task is owned by TaskHeap in AsyncTaskChain, but `cleanup_task()` is called after the task is erased from TaskHeap. So, I moved the task holder before the erasing and removed it in `cleanup_task()`.
(Another lines have already task holders.)
p.s. I can easily reproduce this crash using following codes.
```.cpp
PT(AsyncTaskManager) taskMgr = AsyncTaskManager::get_global_ptr();
taskMgr->add(new GenericAsyncTask("Accumulator", &task_func, (void*)NULL));
// do the main loop, equal to run() in python
framework.main_loop();
taskMgr->remove(taskMgr->find_task("Accumulator"));   // crash!
```

event: fix a crash when removing a task is not owned by user

---

panda/src/bullet/bulletWorld.cxx

- Release the global lock during the user tick callback
and allow interactions with bullet world
- Acquire the lock again after the callback

bullet: Allow intractions with bullet world during tick callbacks

---

direct/CMakeLists.txt

Currently, the libp3direct shared object and any symlinks associated with it are not included in the install process for the direct library. This MR adds the necessary install directive to direct's CMakeLists in order to rectify this behaviour.

cmake: Fix install procedure for direct

---

panda/src/express/checksumHashGenerator.I

`WIN32_LEAN_AND_MEAN` macro redefinition warning happens in some C++ projects although it does not happen while compiling Panda3D. This PR fixes it.

Fix macro redefinition warning

---

pandatool/src/maya/maya_funcs.T

Hello. I fixed compilation error in Maya tool caused by missing std namespace.

pandatool/maya: Fix compilation error by missing std namespace

---

direct/src/showbase/Transitions.py

This allows the 'blendType' argument to be passed through the three transitions' Lerp Intervals.

showbase: Add blendType argument for Fade/Iris/Letterbox

---

panda/src/chan/partBundle.h

This fixes link error by missing export macro in stream functions for `PartBundle::BlendType`.

chan: add missing export macro

---

dtool/src/dtoolbase/dtoolbase.h

Hello! This PR fixes redefinition warning of NOMINMAX macro.

dtoolbase: fix NOMINMAX macro redefinition warning

---

dtool/src/interrogatedb/py_panda.cxx

If `main_module` was a nullptr (which may happen in certain cases), `PyObject_GetAttrString(main_module, "__file__")` would segfault.

Dtool_PyModuleInitHelper: Fix segfault

---

dtool/src/dtoolbase/typeHandle.cxx
dtool/src/dtoolbase/typeHandle.h
dtool/src/dtoolbase/typeRegistry.cxx
dtool/src/dtoolbase/typeRegistry.h
dtool/src/dtoolbase/typeRegistryNode.I
dtool/src/dtoolbase/typeRegistryNode.cxx
dtool/src/dtoolbase/typeRegistryNode.h
dtool/src/interrogate/interfaceMakerPythonNative.cxx
dtool/src/interrogate/interrogate_module.cxx
dtool/src/interrogatedb/py_panda.I
dtool/src/interrogatedb/py_panda.cxx
dtool/src/interrogatedb/py_panda.h

This is the first step to solving #387, based on the suggestion in [my latest comment](https://github.com/panda3d/panda3d/issues/387#issuecomment-435705406).  It does two things:
- It replaces the dynamic type map with a `PyObject *` stored on TypeRegistryNode.  This is used for resolving a TypeHandle to the corresponding Python type.  It seems justified to rely on dtool for this one since using TypedObject adds a dependency on dtool anyway.  This does not create any dependency on a particular Python ABI, since it is just a forward declaration, so effectively a void pointer.
- It moves the "named type map" to the Python interpreter state, for resolving types defined in the global C++ namespace by their fully scoped name.  No dependency on dtool needed for this one.
Thereby, it clears the …

Remove Python type tables from interrogatedb

---

panda/src/bullet/bulletCapsuleShape.cxx

Functions get_point_a() and get_point_b() appear to return the top of the cylinder section of the tube, not the tip of the endcap, making subtracting the radius unnecessary.

Fix BulletCapsuleShape creation from Panda CollisionTube

---

panda/src/windisplay/winGraphicsWindow.cxx
panda/src/x11display/x11GraphicsWindow.cxx

After merging 7ed8b01a commit, a crash happens on patched line of `get_pointer()`.
I fixed it to pointer casting because `_input_devices` is vector of pointer.
ps. I don't know why there was no problem previously.

display: fix pointer casting in get_pointer()

---

panda/src/cocoadisplay/cocoaPandaView.mm

It looks like this only happens when building with the 10.14 SDK, which is why we were seeing it so inconsistently. Fixes #414.

Fix the flickering issue in macOS 10.14

---

panda/src/x11display/x11GraphicsWindow.cxx

This fixes #393 and seems to work fine with the mouse_mode sample app.

x11display: Do not grab the mouse in confined mode when the window does not have focus

---

panda/src/pgraph/billboardEffect.cxx

In older BAM files (version <= 6.42), _fixed_depth will have an uncertain value after loading, leading to incorrect transform calculations, which cause rendering issues (see issue #474).
This commit sets _fixed_depth to false when loading older models, which restores the correct legacy behavior.
Fixes issue #474.

pgraph: fix BillboardEffect regression with older models

---

panda/src/cocoadisplay/cocoaGraphicsWindow.mm
panda/src/cocoadisplay/cocoaPandaWindowDelegate.h
panda/src/cocoadisplay/cocoaPandaWindowDelegate.mm

This commit also removes an extraneous call to [_window setReleasedWhenClosed], which is already set in cocoaPandaWindow's init method. Fixes #534.

Fix an instance where a macOS window will stick around when trying to have it destroyed.

---

.github/workflows/ci.yml

This adds CI using the GitHub Actions beta for Ubuntu, macOS and Windows.  I didn't spend much effort on this, but it's a stub that we can use to replace Travis (and eventually, BuildBot); it's already better than Travis in that it can build on the major three platforms (and also supports Docker containers).  We can add CMake as a separate job.
The main downside appears to be that GitHub Actions doesn't have IRC or Discord notifiers yet, but this could be done using custom action steps (or by using `curl` to poke a webhook).
We can actually upload artifacts for a build, but this is not yet done.

Use GitHub Actions for continuous integration

---

dtool/src/interrogatedb/py_panda.cxx
dtool/src/interrogatedb/py_wrappers.cxx
panda/src/event/asyncFuture_ext.cxx
panda/src/event/pythonTask.cxx

The intended purpose of this function is to restore an exception
that has already been raised and saved with PyErr_Fetch. It should
not be used to raise new exceptions nor should it be used to clear
the current exception.
The especially egregious example is
`PyErr_Restore(exc_type, nullptr, nullptr);`
as the null value may not be handled correctly.

general: Don't abuse PyErr_Restore

---

direct/src/dist/commands.py

build_apps: Fix defaults for package_data_dirs

---

.gitignore
dtool/src/dtoolutil/textEncoder.h
panda/src/bullet/bulletDebugNode.h
panda/src/express/virtualFileMountRamdisk.h
panda/src/gobj/geom.h
panda/src/gobj/lens.h
panda/src/gobj/vertexDataSaveFile.cxx
panda/src/pnmimage/convert_srgb.h

I am dividing the pull request #791 and adding into the main branch as requested
Those changes add EXPCLs to sub classes in some classes. Because without then, linking errors ocurred with clang in windows while using mingw32 in Msys2

Added EXPCLs to fix linking errors with clang in windows

---

panda/src/cocoadisplay/cocoaGraphicsWindow.mm

Simple fix for #794, HiDPI mode is always disabled when creating the NSView for the current window.
(Note: only tested on Catalina I want to see if it passes the CI, I will test later on Mojave)

MacOS: Force disable HiDPI on NSView

---

panda/src/cocoadisplay/cocoaGraphicsWindow.mm

While testing on a screen with a scale factor of 1.75 instead of the usual factor 2.0 I discovered a difference of behaviour between Panda3D compiled with macOS SDK 10.6 vs macOS SDK 10.9 if the fullscreen resolution used is the resolution of the screen (as seen by the application) and not one of the resolution returned by getDisplayInformation()
On that screen, the screen resolution seen by the application is 1920x1200 (i.e. 3360, 2100 / 1.75), the list of supported resolution is [[3360, 2100], [2880, 1800], [2560, 1600], [2048, 1280], [1650, 1050], [1440, 900], [1280, 800], [1152, 720], [1024, 768], [840, 524], [800, 600], [640, 480]] (getDisplayInformation() returns the screen resolutions with scale factor 1.0)
On Panda3D macOS 10.6, if the current mode resolution is the same as the …

cocoadisplay: Fix switch to fullscreen on macOS 10.9 using current display resolution

---

makepanda/makepandacore.py

see chrome specific preloading at https://emscripten.org/docs/porting/files/packaging_files.html#preloading-files

[webgl-port] wasm/wasi should use .so suffix whereever possible

---

direct/src/showbase/PythonUtil.py

Nothing too complicated here; just fixing two uses of reduce() which has been moved to functools in Python 3.
Simply using the reduce() now part of the Python functools module.

PythonUtil: Fix usage of reduce() for Python 3

---

panda/src/pgraphnodes/shaderGenerator.cxx
tests/display/test_color_buffer.py

The material alpha overrides alpha values from flat color or vertex
colors. This follows what the fixed-function pipeline does.
Fixes #912

shadergen: Make use of material alpha if present

---

panda/src/putil/uniqueIdAllocator.cxx
panda/src/putil/uniqueIdAllocator.h
tests/putil/test_uniqueidallocator.py

Currently, using the "free" method on an UniqueIdAllocator is relatively dangerous.
If you free an ID that has not been allocated yet, you will trigger an `_table[index] == IndexAllocated`  assert on debug builds. (I presume it causes a crash on release builds.)
A previous commit, fb0807d7696142d403bb6b18e14acabbdf2b9308, attempted to solve this issue by adding an `is_allocated` function, which could be called before freeing an ID.
However, we haven't considered the fact that UniqueIdAllocators might be used by more than one thread at once!
What happens if you check if an ID is allocated, then attempt to free it while another thread frees it in the background?
Even though you've checked for the allocation state already, since some other thread has already freed that ID, you'll run into …

putil: Turn UniqueIdAllocator's free into an atomic operation

---

panda/src/cocoadisplay/cocoaGraphicsWindow.mm

This PR aim to fix the regression described in #1001, causing functions key to no longer work on MacBook where they are used in conjunction with the Fn key.
If UCKeyTranslate could not map the key into a valid unicode character or reserved symbol (See NSEvent.h), it returns 0x10 as translated character. This happens e.g.e with the combination Fn+F1.. keys (but for weird reasons not for the arrow keys).
In that case, as fallback, we use [event charactersIgnoringModifiers] to retrieve the character without modifiers.

cocoadisplay: Use [event charactersIgnoringModifiers] when UCKeyTranslate() can not translate the input key

---

direct/src/dist/commands.py

When downloading wheels as part of `build_apps`, pip will issue warnings about a newer version of pip being available. If the user is not using the latest version of pip, they will likely be
spammed by pip enough as is. There is not much need to remind them about this for each built platform.
Pass `--disable-pip-version-check` to pip when downloading wheels.

build_apps: Disable the pip version check when downloading wheels

---

panda/src/audiotraits/openalAudioSound.cxx

Calling `setActive(False)` on a sound is intended to pause the sound, and a future call to `setActive(True)` is intended to resume the paused sound.  Paused sounds were being restarted instead of resumed where they left off.
Before pausing the sound, store the current time as the start time for when the sound is resumed.  This is what the Miles implementation did, and what FMOD _tries_ to do, but the start time is mistakenly overridden to 0 (I'm working on improving FMOD).

openal: Fix paused sounds not resuming from where they were paused

---

direct/src/directtools/DirectSession.py

Similar to #977, the Direct Session UI includes 3 Readouts that are positioned to be in the corners, however they are parented to aspect2d. This PR realigns them to the corners, and updates the design to be more in line with other parts of panda, like the FPS meter (white text on a translucent black background)

Cleaner Direct Session Readouts UI

---

makepanda/makepanda.py

FFTW3 is not found when building on Alpine Linux.
Adding fftw3's pkg-config name ensures that makepanda can use pkg-config to find the fftw3 libraries.

makepanda: Add fftw3 pkg-config name

---

direct/src/dist/FreezeTool.py
direct/src/dist/commands.py

This is exposed as a hidden_imports option, which is a dictionary. The
keys are module name and the values are a list of modules to include
when an import for the key is found.
Currently hidden imports can only be addressed by modifying FreezeTool directly. Users *can* work around this by specifying `include_modules`. However, this is not ideal for tools such as [pman](https://github.com/Moguri/pman) that may want to conditionally include modules or if we expose pkg_resources entry point hooks for packages to modify this variable themselves.
This PR allows a user to specify `hidden_imports` which will get added to the ones already in FreezeTool. 

build_apps: Allow setting hidden imports via setuptools options

---

panda/src/glstuff/glShaderContext_src.cxx
panda/src/gobj/shader.I
panda/src/gobj/shader.cxx
panda/src/gobj/shader.h
panda/src/gobj/shaderModule.I
panda/src/gobj/shaderModule.h
panda/src/shaderpipeline/shaderModuleSpirV.cxx
panda/src/shaderpipeline/shaderModuleSpirV.h

Adds support for specialization constants to the shaderpipeline branch.  Can be used in place of preprocessor definitions to set values that are constant for the entire shader, without requiring a complete recompilation of the shader from source.
Each `ShaderModule` contains a list of `SpecializationConstants`, which individually store the name, type, and constant ID.  `ShaderModuleSpirV` fills in that list when parsing the SPIR-V instructions.  In `Shader`, external values given to the constants are stored per-module in two lists with matching indices: the constant IDs and the values.  To set a constant from application code, the usage is `Shader.set_constant(name, value)`.  The matchup is done by name, so multiple shader modules containing a spec constant with the same name are given …

shaderpipeline: add support for specialization constants

---

direct/src/actor/Actor.py

Actors were acting up in extraordinary ways!
Turns out that the Actor `__init__` method was broken in be9dde1eee22e8d83c44399f042c1a12aa18942a.
If Actor_initialized is set, actors will not be re-initialized anymore (this has always been the default behavior)

direct: Fix actor initialization

---

panda/src/bullet/bulletGhostNode.cxx
panda/src/bullet/bulletGhostNode.h
panda/src/bullet/config_bullet.cxx
tests/bullet/test_bullet_bam.py

Allows bullet ghost nodes to be serialized.
Fixes #1099 
Add bam serialization/deserialization files

Serialize BulletGhostNodes

---

direct/src/distributed/ClockDelta.py

ConfigVariableBool is not defined in direct/src/distributed/ClockDelta.py. ClockDelta cannot be used. This is a regression from 3fe1780f1678c562b669a5263cbff306db460be8: I've checked all other edited files to make sure they import.
Import ConfigVariableBool from panda3d.core.

direct: Fix undefined ConfigVariableBool name in ClockDelta

---

makepanda/makepanda.py
makepanda/makewheel.py

Add manylinux_2_24 as a wheel target
Stubs things out just as is done for the other manylinux platforms.

Add manylinux_2_24 for building

---

makepanda/makepanda.py
makepanda/makewheel.py

Fixes an error introduced with a723567a3a4a32a1f7167bcb049aeea5b69ab7cf - the search path was not complete, and caused 64-bit wheels to not properly detect as `manylinux_2_24`.
I think this must have been a copy error on my part...?
In any case, I have built the wheel from the live version of the repository this time around (as opposed to building off a local clone).

Correct location searched for 64-bit libc-2.24

---

direct/src/showbase/PythonUtil.py

This PR removes the Enum (and inner EnumIter class) from `PythonUtil.py`.
Since Python 3.4+ has various Enum classes in the stdlib they should be used instead.
Removed Enum class and EnumIter class which are not used anywhere else anymore.

Remove Enum class from PythonUtils.

---

makepanda/makepandacore.py

We don't need the extra precision, in fact it is detrimental to restoring build caches in a cross-platform way.
This commit will invalidate all current build caches.
The makepanda system currently saves the last built timestamps encountered for each file. This can be a problem when caching the `built` folder of a build attempt, as the saved / restored granularity of the timestamps might not match between different platforms, leading to the build cache being completely disregarded after being restored.
This pull request resolves this problem by storing timestamps as integers in the build cache. It also increments the version number of the build cache, leading to a single rebuild being required after pulling this change.

makepanda: Record cache timestamps as integers rather than floats

---

pandatool/src/mayaprogs/mayaConversionClient.cxx
pandatool/src/mayaprogs/mayaConversionClient.h
pandatool/src/mayaprogs/mayaConversionServer.cxx
pandatool/src/mayaprogs/mayaConversionServer.h

As @rdb has pointed out, `MayaConversionClient` is creating three objects on the heap but neglecting to clean it up in a missing destructor.
Instead of creating a destructor, I've decided to take the objects off the heap completely. Instead, the constructor will initialize these connection management objects directly on the object on both `MayaConversionClient` and `MayaConversionServer`.

mayaprogs: Resolve Maya conversion server memory leak by storing managers on the heap

---

panda/src/device/config_device.cxx

Fixes mising InputDeviceNode from type db, possible cause of crashes in opt 4 mode

device: Fix missing init_type for InputDeviceNode

---

direct/src/dcparser/dcPacker_ext.cxx

The `long` type is 32 bits on Windows and 64 bits on most linux systems. Therefore, passing an uint32 value to `PyLong_FromLong` on Windows converts it to a signed 32 bit integer.
Replacing `PyLong_FromLong` to `PyLong_FromUnsignedLong` should fix the issue

dcparser: fix uint32s being signed on Windows

---

panda/src/mathutil/triangulator.cxx

See first paragraph of https://graphics.stanford.edu/courses/cs268-09-winter/notes/handout6.pdf
I'm trying to learn about trapezoidation, and I found this code. A [comment](https://github.com/panda3d/panda3d/blob/master/panda/src/mathutil/triangulator.cxx#L128) in triangulator.cxx suggests that the randomization process is skipped, [but it exists to ensure the algorithm performs in O(n*log(n)) time on average.](https://graphics.stanford.edu/courses/cs268-09-winter/notes/handout6.pdf)
It shuffles afterward anyway to dodge errors, so there's no problem, but it could be misleading to maintainers.
I corrected the comment, but left functionality unchanged
* [ x] …I have familiarized myself with the CONTRIBUTING.md file
* [ x] …this change follows the coding …

Correct documentation

---

direct/src/distributed/cConnectionRepository.cxx
panda/src/downloader/socketStream.I
panda/src/downloader/socketStream.h
panda/src/recorder/socketStreamRecorder.I

This corrects an instance of covariant overload on return type. Such functionality is generally a dangerous pattern in C++. See [Issue #1418](https://github.com/panda3d/panda3d/issues/1418)
I changed `SSWriter::flush()` (and derived types) to return `void` rather than `bool`, then adjusted call sites to call `is_closed()` if they needed that information.

fix SocketStream::flush() covariant

---

panda/src/putil/bitArray.I
panda/src/putil/bitArray.cxx
panda/src/putil/bitArray.h

Fixes #1425 
One solution path. I changed the return type of `get_word()` to be the "word type". This is symmetric with the `set_word(...)` method. For internal computations that want some of the `BitMask<....>` functionality, the former implementation of `get_word()` is moved into a private `get_word_internal()` method that continues to return the `MaskType`. Internal calculation can continue to operate on that. The new `get_word()` implementation calls `get_word_internal()` and extracts the actual word to return.
An alternative may be to not export `get_word()`, but that seems overly constrained.
@rdb has also suggested making `set_word(...)` take `MaskType`. For myself this feels like exposing implementation detail. But I'm not especially passionate about either direction.
I have done …

patch around non-exported return type

---

direct/src/showbase/ShowBase.py

This PR aims to solve issue #1402 - Make ShowBase use a private DirectObject for window-event
This PR solves this problem by creating an internal instance of DirectObject (self.__directObject) and using that for showbase's internal accepts (window-event and oobe)

ShowBase: Add a private DirectObject to allow use of base.accept for window-events

---

direct/src/directnotify/Notifier.py

This PR solves issue #1247  where it was requested that Notifier should have a custom exception type.
This PR solves this by defining NotifierException at the top of the file, and setting that as the default parameter for exception in the error method.

Notifier: Add custom exception type for Notifier.error

---

direct/src/dist/commands.py

When `bdist_apps` is ran with `skip_build` set to `False`, we call `build_apps.finalize_options` twice. As  https://github.com/panda3d/panda3d/commit/3f3fd74f869b21b249e76d3068cb1735afa807ae we trigger an AssertionError if a `bam_model_extension` already exists in `file_handlers`. 
This PR moves the `build_cmd.finalize_options()` call to an `else` block, so that we don't call `finalize_options` twice.

bdist_apps: Fix assertion error from calling finalize_options twice

---

panda/src/bullet/bulletBodyNode.cxx
panda/src/bullet/bulletBodyNode.h

This is useful for example when the collision node is rotated, is not centered to origin, or has several parent transforms applied on it.
Code is much the same as original, so adapt original function to use the expanded one.

Extend BulletBodyNode::add_shapes_from_collision_solids() to accept a TransformState

---

dtool/src/interrogate/interfaceMakerPythonNative.cxx
dtool/src/interrogatedb/py_compat.h
dtool/src/interrogatedb/py_panda.cxx
dtool/src/interrogatedb/py_panda.h
dtool/src/interrogatedb/py_wrappers.cxx
panda/src/event/asyncFuture_ext.cxx
panda/src/gobj/pythonTexturePoolFilter.cxx
panda/src/pgraph/nodePath_ext.cxx
panda/src/pgraph/pythonLoaderFileType.cxx
panda/src/pgraph/renderState_ext.cxx
pandatool/src/deploy-stub/android_main.cxx

The private `_PyErr_OCCURRED` macro was removed in Python 3.10.0 alpha 5: https://bugs.python.org/issue43270
While building Panda3D for Python 3.12.0 alpha 5, I noticed that Panda3D's `py_compat.h` header was erroneously defining `_PyErr_OCCURRED` as:
```cpp
PyThreadState_GET()->curexc_type
```
However, Python 3.12.0 alpha 5 no longer has a  `curexc_type` field as part of the `PyThreadState` struct. This causes the build to fail.
Problem 1: `py_compat.h` should not be redefining the `_PyErr_OCCURRED` macro for all Python versions. The invalid macro definition only exists prior to Python 3.3.3. It comes as a surprise that it is being redefined in all subsequent Python versions also. This can lead to issues if newer Python versions have a different implementation of the macro.
Problem 2: …

python: Use public PyErr_Occurred API instead of private macro

---

direct/src/showbase/Loader.py

Fixes `NameError: name 'SamplerState' is not defined` after c7c70bc32a298557684c58065bae5a02c1cb72ba . 
This was the only issue I've encountered in some simple testing of my application.
Added missing import

direct: fix missing import in Loader

---

panda/src/egg/eggTexture.cxx
panda/src/egg/eggTexture.h
panda/src/egg2pg/eggLoader.cxx
panda/src/egg2pg/eggSaver.cxx
pandatool/src/egg-palettize/eggPalettize.cxx
pandatool/src/palettizer/palettizer.cxx
pandatool/src/palettizer/textureImage.cxx
pandatool/src/palettizer/textureProperties.cxx
pandatool/src/palettizer/textureProperties.h
pandatool/src/palettizer/textureRequest.cxx
pandatool/src/palettizer/textureRequest.h
pandatool/src/palettizer/txaLine.cxx
pandatool/src/palettizer/txaLine.h

This PR adds sRGB texture support to egg-palettize, and adds the sluminance and sluminance_alpha formats to egg.  Previously, there was no way to tell egg-palettize that a texture is in sRGB space.
A new `srgb` keyword is made available in `textures.txa`.  This specifies that a texture is in the sRGB color space and the format of the texture should be changed to the appropriate sRGB equivalent based on the number of image channels or requested number of channels.  The resulting palette will also end up with an sRGB texture format.
```
hands.rgb : 256 256 mipmap srgb
```

add sRGB support to egg-palettize, sluminance to egg

---

pandatool/src/palettizer/textureProperties.cxx

Alpha-only textures shouldn't be changed to sluminance.

palettizer: don't respect srgb flag for alpha textures

---

.github/workflows/ci.yml

Ubuntu 18.04 can no longer be built in workflows as of today, must migrate to continue support
Migrating from Ubuntu 18.04 and remove an unnecessary line

workflow: Migrate to Ubuntu 20.04, remove unnecessary line.

---

dtool/src/dtoolutil/executionEnvironment.cxx

When compiling Panda3D with Mingw64, Panda3D attempts to call the `setenv` function which is not available on Mingw64. However, `_putenv_s` and friends are available on Mingw64 just fine.
I've replaced the `_MSC_VER` macros in `ExecutionEnvironment` with `_WIN32` macros which should apply to both MSVC and Mingw64.

dtoolutil: Fix _MSC_VER macros that should be _WIN32

---

panda/src/cocoadisplay/cocoaGraphicsPipe.mm

Recent changes in cocoadisplay codes introduces warnings during the compilation due to some now missing includes that were probably included indirectly.
Note: This is on macOS 12.1 x86 using SDK 10.9
<pre>
panda/src/cocoadisplay/cocoaGraphicsPipe.mm:35:3: error: use of undeclared identifier 'NSThread'; did you mean 'NewThread'?
NSThread* thread = [[NSThread alloc] init];
^~~~~~~~
NewThread
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Threads.h:444:1: note: 'NewThread' declared here
NewThread(
^
In file included from panda/src/cocoadisplay/p3cocoadisplay_composite1.mm:1:
panda/src/cocoadisplay/cocoaGraphicsPipe.mm:35:24: error: use of undeclared …

cocoadisplay: Fix compilation errors and warnings due to missing includes

---

dtool/src/interrogatedb/py_panda.cxx
panda/src/pgraph/renderState_ext.cxx

Python 3.13 has unpublished the _PyUnicode_EqualToASCIIString private C API call. It is now part of the internal API: https://github.com/python/cpython/issues/106320
This pull request replaces the private _PyUnicode_EqualToASCIIString API call with the similar public PyUnicode_CompareWithASCIIString API call.

python: Remove usage of private _PyUnicode C API calls

---

direct/src/distributed/ClientRepositoryBase.py

Currently, if DO object updates are handled in Python in ConnectionRepositoryBase, and the repository does not have owner view, then the engine will crash as `__doUpdateOwner` will attempt to access an undefined dictionary `doId2ownerView`.
This pull request simply adds a check in `__doUpdateOwner` to see if the repository has owner view and returns early if not, so the nonexistent property is not accessed.

Properly handle update fields in Python if ConnectionRepositoryBase does not have owner view.

---

direct/src/distributed/MsgTypes.py

Distributed MsgTypes is missing certain control (MD) messages, mostly used for telemetry and debugging.
Added the missing message types. See [Astron](https://github.com/Astron/Astron/blob/master/src/core/msgtypes.h#L39) and [Ardos](https://github.com/ksmit799/Ardos/blob/main/src/net/message_types.h#L41) for reference.

Added missing control message types

---

direct/src/dist/commands.py
panda/src/cocoadisplay/cocoaGraphicsPipe.mm
panda/src/cocoadisplay/cocoaGraphicsWindow.h
panda/src/cocoadisplay/cocoaGraphicsWindow.mm
panda/src/cocoadisplay/cocoaPandaWindowDelegate.h
panda/src/cocoadisplay/cocoaPandaWindowDelegate.mm
panda/src/cocoadisplay/config_cocoadisplay.h
panda/src/cocoadisplay/config_cocoadisplay.mm

This PR add High-DPI support on macOS. Until now, on macOS a Panda3D application was not "dpi-aware" and so the OpenGL view was upscaled by the system. With this PR, an application can set `dpi-aware` to `true` to disable the scaling on High-DPI/Retina screen and use the full resolution of the display.
See also the discussion here : https://discourse.panda3d.org/t/updated-there-is-no-retina-support-on-mac-catalina-big-sur/27946
On macOS, an application should not be aware of the actual pixel density of a screen, the application uses display points that are then transformed into actual pixel coordinates by appkit. Pixel units (or more exactly backing store points), are to be used only for some specific case. On the other hand, in the philosophy of the High-DPI support of Panda3D the unit …

cocoadisplay: Add support for high-dpi screens

---

panda/src/pgui/pgEntry.h
panda/src/pgui/pgFrameStyle.h
panda/src/pgui/pgItem.h
panda/src/pgui/pgScrollFrame.h
panda/src/pgui/pgSliderBar.h
panda/src/pgui/pgTop.h
panda/src/pgui/pgVirtualFrame.h
panda/src/pgui/pgWaitBar.h

These changes just allow for property-style access from Python to data in various `pgui` classes.

pgui: Add more property-style accessors

---

panda/src/bullet/bulletContactCallbacks.h

This change addresses note 2 within issue #1562.
This change assumes the mutex for BulletWorld is already locked (as it should be in `do_physics`), and releases the mutex before calling the contact added callback, then reacquires the mutex. 

bullet: Fix deadlock when contact added callback accesses certain data or executes bullet methods

---

pandatool/src/gtk-stats/gtkStatsMonitor.cxx
pandatool/src/gtk-stats/gtkStatsServer.cxx

Workaround implementation to solve https://github.com/panda3d/panda3d/issues/1605
As workaround for https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2029, we manually create a GtkFlowBoxChild instance and attach the label to it and increase its reference count so it it not prematurely destroyed when removed from the GtkFlowBox, causing the UI to segfault.
I am unsure if `GtkStatsMonitor::_status_bar_labels` and `GtkStatsServer::_status_bar_label` should have been renamed or not as they now store `GtkFlowBoxChild` instead of `GtkLabel`. I thought the renaming would be too invasive.

pstats: Workaround for Gtk bug that causes UI to crash when a session is closed

---

panda/src/linmath/lmatrix3_ext_src.h
panda/src/linmath/lmatrix4_ext_src.h
panda/src/linmath/lpoint2_ext_src.h
panda/src/linmath/lpoint3_ext_src.h
panda/src/linmath/lpoint4_ext_src.h
panda/src/linmath/lvecBase2_ext_src.h
panda/src/linmath/lvecBase3_ext_src.h
panda/src/linmath/lvecBase4_ext_src.h
panda/src/linmath/lvector2_ext_src.h
panda/src/linmath/lvector3_ext_src.h
panda/src/linmath/lvector4_ext_src.h
panda/src/pipeline/CMakeLists.txt
panda/src/putil/CMakeLists.txt
panda/src/putil/paramPyObject.cxx

This change adds proper guarding to methods that are specific to python bindings, allowing to build bindings for languages other than Python.
This PR has 2 commits. One focuses on removing `.I` files from `*_IGATEEXT` cmake variables since the `.I` files are not guarded for python support. The second adds some missing python guarding in a few header files.

Guard python specific extensions

---

direct/src/interval/cInterval_ext.cxx
dtool/src/dtoolutil/iostream_ext.cxx
panda/src/event/asyncFuture_ext.cxx

Building Panda3D with `CMAKE_UNITY_BUILD_BATCH_SIZE` set to a ridiculously large number (like 500) results in a compilation error due to `gen_next` being redefined multiple times.
Rename `gen_next` in each extension to provide a unique name in each case. Feel free to change the names I've chosen if they are inadequate.

ext: Use different names for each gen_next method

---

cmake/macros/Interrogate.cmake
direct/src/cluster/ClusterClient.py
direct/src/cluster/ClusterMsgs.py
direct/src/cluster/ClusterServer.py
direct/src/distributed/ServerRepository.py
makepanda/makepanda.py
panda/CMakeLists.txt
panda/src/nativenet/CMakeLists.txt
panda/src/net/CMakeLists.txt
tests/test_imports.py

This change is intended to prepare for #1466, which is about moving the net and nativenet classes to a separate `panda3d.net` module, while retaining compatibility for now.
For compatibility, the classes remain in `panda3d.core`, but there is a new `panda3d/net.py` file that specifically imports those classes from `panda3d.core`.  Regardless of where they are imported from, they do have a `__module__` field of `panda3d.net`.

Forward compatibility for splitting off net classes to separate panda3d.net

---

direct/src/actor/Actor.py
panda/src/putil/animInterface.I
panda/src/putil/animInterface.h

As of right now there is not a way to know in which way an Actor is currently playing an animation (playing, looping, etc.) This PR fixes it.
I've published a getter for play_mode in AnimInterface and exposed a helper on Actor. since getAnimControls() didn't used to return controls that are not playing anything, it made the helper not work in Pose mode, so I added an optional argument to control that.

add getPlayMode() for actor and anim interface

---

dtool/src/interrogate/interfaceMakerPythonNative.cxx

After https://github.com/panda3d/panda3d/commit/38692dd525525e20cd06204a646b35dd7e39902a, GC pauses occuring before
the `__init__` function of the C++ backed object is called in a inheritance chain will
cause an exception during garbage collection and cause the python runtime to exit.
This can be observed by say, forcing a GC-pause in `MetaInterval.__init__` before it calls `CMetaInterval::__init__`.
This change replaces the call to Dtool_Call_ExtractThisPointer with a direct check for whether DtoolInstance_VOID_PTR is nullptr and exit with status 0 if that's the case, rather than raising an exception.

interrogate: avoid GC exceptions processing objects mid-construction

---

panda/src/event/pythonTask.cxx
tests/event/test_futures.py

A missing Py_DECREF on the future's "done" method
caused both the bound method and the underlying
self instance of the future to be leaked when
awaiting non-panda futures (such as _asyncio.Future).
This change includes a simple new test addition
to catch this in the future.
Add the missing Py_DECREF call and a new unit-test to cover this area.

pythonTask: fix refcount leak of non-panda Future::done

---

direct/src/showbase/Transitions.py

What is this change intended to accomplish?  What problem does it solve?
Since the Fade Transitions has these functions to get the interval, it only makes sense to make some for Iris as well.
Solution description
It is useful to use these functions for Iris transitions in Sequences and Parallels rather than something weird like:
`sequence = Sequence(Func(base.transitions.irisIn(5)), Wait(5))`

showbase: Add functions to get interval for Iris Transitions

---

panda/src/event/pythonTask.cxx
tests/event/test_pythontask.py

"event: use the persistent python wrapper when appending task object to args"
Seems to fix #1680 but also this is a nice optimization regardless since we no longer need to create a new python wrapper object every time we call into python.
Also fixes subclassing of PythonTask not passing in the subclass instance to the task function.
Don't create a new wrapper object if one exists when appending the task object to the function arguments, instead pass in a new reference to the existing `__self__` object

event: use the persistent python wrapper when appending task object

---

panda/src/event/asyncFuture_ext.cxx
tests/event/test_futures.py

Raising the StopIteration exception left the underlying result with an elevated refcount which prevented it from being cleaned up.
Running the new test (test_await_future_result_cleanup) on current master results in the result object of an AsyncFuture (or associated friends like AsyncGatheringFuture and PythonTask) being left with a permanently elevated refcount introduced when `await`ing the future.
Properly account for PyErr_SetObject raising the refcount of `result` from get_done_result and add a test to help cover this path for the future.

event: fix result refcount leak when awaiting AsyncFuture

---

panda/src/testbed/pview.cxx

This is basically an RFC for the following change:
Adds a simple bind (shift+r) to reload all textures in the TexturePool in pview, to reduce the friction of edit texture -> exit pview -> reopen pview -> repeat.

pview: add shift+r keyboard bind to reload all textures

---

direct/src/showbase/Transitions.py

When I implemented my Iris intervals, there was a duplicated line I missed causing rare occurrences for Iris intervals to give a blank black screen. This patch will fix that.
Remove a duplicated line adding the finish interval.

showbase: Patch for iris intervals

---

direct/src/directbase/TestStart.py
direct/src/directbase/ThreeUpStart.py
direct/src/showbase/ShowBase.py

These changes add type annotations to some basic `ShowBase` methods used on setup and shutdown. This mostly comprises adding annotations to attributes assigned in `ShowBase.__init__`. See also #1217, which aimed to do mostly the same thing, but seems to have been abandoned.

showbase: Annotate basic `ShowBase` setup/shutdown methods

---

panda/src/windisplay/winGraphicsWindow.cxx

Added a case in switch inside window_proc function in winGraphicsWindow.cxx file to prevent the window from being resized to a height of 0 and a width of less than 120. 
Issue https://github.com/panda3d/panda3d/issues/1689
On windows now the minimum window width now is 120 and minimum height is 1.
This prevents the occurrence division-by-zero errors, creation of invalid textures, etc. 

Prevent window resize to zero

---

panda/src/cull/cullBinBackToFront.cxx
panda/src/cull/cullBinFrontToBack.cxx

Panda3D crashes when an object with an empty volume is culled after commit https://github.com/panda3d/panda3d/commit/6823634f60a652be80b7ed627d1d11a2cea1e6c0.
This is caused by Panda3D attempting to free the cullable object's memory. This didn't use to be a problem before, but now that the CullableObject is part of an allocation table managed by CullResult's allocation table, we can't free the object itself since it is part of a larger allocation table object.
Remove the object deletion. When `CullResult` is deleted, the allocation table the CullableObject is part of will be deleted anyway.

cull: Fix crash caused by freeing a cull object with empty volume

---

direct/src/showbase/ShowBase.py

These changes annotate the callback methods (and methods called by those methods) on `ShowBase` that are used by code that is already type-hinted. Of note is the fact that many of these take a second argument that is unused. I have elected to annotate these arguments with `object` to signify that any object can be passed here, but something like `AsyncTask` or `AsyncTask | None` is also an option.

showbase: Annotate callback methods

---

direct/src/showbase/Loader.py
tests/showbase/test_Loader.py

These changes annotate methods of `Loader` that are used in the test suite or other type-annotated code. There is a way to use overloads to describe the relationship between parameter and return types for `loadModel`, but it's [quite verbose](https://github.com/WMOkiishi/types-panda3d/blob/cfad0b9aa00607c16cad95e0afd9a2fd5d454f73/src/direct-stubs/showbase/Loader.pyi#L69-L207), so I've just annotated the return type as `Any`.
There is also a slight change to the tests so that `Loader.destroy()` is also tested.

showbase: Annotate basic `Loader` methods

---

direct/src/distributed/ClockDelta.py
direct/src/extensions_native/extension_native_helpers.py
direct/src/showbase/PythonUtil.py
direct/src/showbase/ShowBase.py
direct/src/stdpy/thread.py
direct/src/stdpy/threading2.py
direct/src/tkpanels/Inspector.py

These changes annotate functions and methods that are called directly by top-level code elsewhere in the library, found by running mypy with the `--disallow-untyped-calls` option. This means that they are run by the test suite (since they run when the file is loaded) and their usage is covered by a type checker (since mypy checks top-level code and annotated functions).

direct: Annotate functions called directly by top-level code

---

dtool/src/dtoolbase/atomicAdjust.h

Tackles #1745 .
Other option would be to change of checks to prefer win32 as @rdb mentioned in the issue.

Use Win32 native calls for atomic also with clang-cl

---

direct/src/showbase/VFSImporter.py

These changes add type annotations to the functions in `VFSImporter` that are called through the test suite. They also correct the signature of `VFSFinder.find_spec`.

showbase: Annotate `VFSImporter` functions

---

direct/src/stdpy/thread.py
direct/src/stdpy/threading.py
direct/src/stdpy/threading2.py

These changes annotate functions in `thread`, `threading`, and `threading2` that are called either by other type-annotated code or through the test suite.

stdpy: Annotate threading functions
