panda3d/panda3d

- makepanda/installpanda.py
- makepanda/makepanda.py
The commit messages should describe nicely what I've changed.
> makepanda.py --installer fixes for dpkg confusion on Fedora and python3

- panda/src/ffmpeg/ffmpegAudioCursor.cxx
- panda/src/ffmpeg/ffmpegVideoCursor.cxx
- panda/src/gobj/samplerContext.h
- panda/src/gobj/samplerState.h
- panda/src/pgraph/cullBinManager.h
- panda/src/pgraph/shaderPool.cxx
This fixes a few bugs I encountered while building against a recent ffmpeg (and with SCU disabled).
> Miscellaneous fixes

- .gitignore
This directory is created during build on Linux.
> Ignore targetroot/ directory

- panda/src/display/graphicsWindow.cxx
- panda/src/display/windowProperties.I
- panda/src/display/windowProperties.cxx
- panda/src/display/windowProperties.h
- panda/src/windisplay/winGraphicsWindow.cxx
- panda/src/windisplay/winGraphicsWindow.h
- panda/src/x11display/x11GraphicsWindow.cxx
- samples/mouse-modes/main.py
Different take on the earlier patch, making use of a third mouse mode.
This moves the X11 absolute/relative handling from mouse_mode_...() methods into set_properties_now.
> Support mouse confinement

- panda/src/rocket/rocketFileInterface.cxx
Moved lookup fix into separate pull request.  Will close other one and update the rocket sample PR.
> Rocket fix file lookup (standalone)

- panda/src/pstatclient/pStatProperties.cxx
Now it is distinct from the "App" category in a default configuration.
> Add pstats star category color

- makepanda/makepanda.py
- pandatool/src/assimp/assimpLoader.cxx
- pandatool/src/assimp/assimpLoader.h
- pandatool/src/assimp/config_assimp.h
- pandatool/src/assimp/p3assimp_composite1.cxx
- pandatool/src/assimp/pandaIOStream.h
- pandatool/src/assimp/pandaIOSystem.h
- pandatool/src/assimp/pandaLogger.cxx
- pandatool/src/assimp/pandaLogger.h
This includes updating header files for Assimp 3.
> Changes to makepanda to compile with Assimp

- direct/src/controls/GravityWalker.py
> Fix invalid assumptions in GravityWalker

- direct/src/stdpy/file.py
I was using foo = open("...", "rt") and getting unexplained errors ("attempt to read from non-opened file" later on).  So I handle 't' and report a unrecognized file mode.
> Accept 't' in mode flags and error out if mode unrecognized

- panda/src/audiotraits/openalAudioSound.cxx
Apologies for the whitespace cleanup (editor does so automatically).
This fixes the assumption that the manager has a volume level of 1.0 when the sound is constructed, and instead uses the volume within the manager.
> openal: Grab volume from manager instead of assuming max volume.

- pandatool/src/assimp/assimpLoader.cxx
We needed to detect islands of bones and create anims and parts for them.
> Assimp: Support skeletons with unconnected bones

- direct/src/gui/DirectEntry.py
> Allow setting width and numLines of DirectEntry without clearing text

- direct/src/gui/DirectGuiBase.py
Risky at best, and actually raises an error on modern Python versions.
> do not mutate dict we are iterating over

- panda/src/bullet/bulletHeightfieldShape.I
- panda/src/bullet/bulletTriangleMesh.cxx
Signed-off-by: deflected <deflected@github>
> bullet: Plug memory leaks

- direct/src/showbase/Loader.py
- panda/src/putil/loaderOptions.I
> loader: Added loading of 2D texture array

- samples/chessboard/main.py
6 spelling mistakes are found in code comments
> Correct several spelling mistakes in Panda3D sample program: Chessboard

- direct/src/filter/CommonFilters.py
- direct/src/filter/filterBloomI.py
- direct/src/filter/filterBloomX.py
- direct/src/filter/filterBloomY.py
- direct/src/filter/filterBlurX.py
- direct/src/filter/filterBlurY.py
- direct/src/filter/filterCopy.py
- direct/src/filter/filterDown4.py
Removed __file__ usage due to unavailability in deploy-ng builds
Moved Cg filters from sha files into separate python scripts
Removed now obsolete loadShader function from CommonFilters
> __file__ usage in CommonFilters

- panda/src/grutil/shaderTerrainMesh.cxx
> grutil: Add control over heightfield filtering in shaderTerrainMesh

- samples/gamepad/flightstick.py
- samples/gamepad/steeringWheel.py
Updated and tested examples for steering wheel and flight stick devices
> Input overhaul updated samples

- panda/src/x11display/x11GraphicsWindow.cxx
> x11display: Release M_relative mouse when window loses focus

- direct/src/leveleditor/ActionMgr.py
- direct/src/leveleditor/CurveEditor.py
- direct/src/leveleditor/FileMgr.py
- direct/src/leveleditor/LayerEditorUI.py
- direct/src/leveleditor/LevelEditor.py
- direct/src/leveleditor/LevelEditorBase.py
- direct/src/leveleditor/LevelEditorStart.py
- direct/src/leveleditor/LevelEditorUIBase.py
- direct/src/leveleditor/ObjectMgrBase.py
- direct/src/leveleditor/ObjectPaletteUI.py
- direct/src/leveleditor/ObjectPropertyUI.py
- direct/src/leveleditor/PaletteTreeCtrl.py
- direct/src/leveleditor/ProtoObjsUI.py
- direct/src/leveleditor/ProtoPaletteUI.py
- direct/src/leveleditor/SceneGraphUIBase.py
- direct/src/leveleditor/testData.py
- direct/src/showbase/ShowBase.py
- direct/src/wxwidgets/WxPandaShell.py
This PR fixes the inbuilt level editor and allows it to run. It is still quite buggy, but it's the start of potentially supplying a basic level editor with new Panda releases. This PR also fixes deprecation warnings/errors associated with wx, which is used within direct.wxwidgets and ShowBase.
> leveleditor: LevelEditor fixes

- pandatool/src/assimp/assimpLoader.cxx
- pandatool/src/assimp/config_assimp.cxx
- pandatool/src/assimp/config_assimp.h
This resolves issue #511 
Fixes #511
> add aiProcess_GenNormals + aiProcess_GenSmoothNormals

- samples/asteroids/main.py
The asteroids sample is reporting errors with the current Pylint configuration.
I have cleaned up the Pylint errors and warnings. I manually tested the sample since I am not familiar with any unit testing on the samples.
> Lint asteroids sample

- panda/src/cocoadisplay/cocoaGraphicsWindow.mm
On macOS, If you ask your app to enter a fullscreen mode with a lower resolution than the desktop then quit the app, when the display is switching back from the fullscreen display mode to the desktop display mode you can observe that all the other windows have been resized to match the size if the fullscreen mode and are resized back to their previous size.
If you have many windows opened (or heavy task running in the background), this resize back is slow and sometimes stops (either because there is a timeout or a bug in Cocoa).
The root cause is that in the current code, the display is captured by the application after switching the display mode. This mode switching triggers a resize event for all the opened windows, and the reverse-resize when the desktop mode is restored.
If the …
> cocoadisplay: Capture display before switching to fullscreen mode

- panda/src/webgldisplay/webGLGraphicsWindow.cxx
MouseData has been renamed PointerData to be more inclusive in https://github.com/panda3d/panda3d/commit/9b85a288616be32dfbb0060b8ce9b435c6beff6d
> wegbgl-port: merge fix

- direct/src/showbase/ShowBase.py
- direct/src/task/Task.py
- tests/task/test_Task.py
These changes add type annotations to the core functions in the `task` module (mostly `TaskManager` methods). Tests have been added for annotated functions that aren't used elsewhere in the codebase. Some additional cleanup had also been done to the existing tests for the `task` module.
> task: Annotate core functions

- panda/src/device/inputDeviceNode.cxx
fixes issue #1571 
improves handling of currently pressed buttons.
> fix small typo, fixes 1571

- direct/src/distributed/ConnectionRepository.py
Inlines ConnectionRepository.generateGlobalObject's applyFieldValues function.
Nested functions [have a performance cost](https://stackoverflow.com/questions/7839632/is-there-an-overhead-when-nesting-functions-in-python), and there's no reason to use a nested function here. I have not `timeit`'d the difference and it probably doesn't matter, but it's Something ™️ 
Inlines ConnectionRepository.generateGlobalObject's applyFieldValues function.
> refactor(distributed): Un-nest generateGlobalObject's applyFieldValues function

- panda/src/pgraph/nodePath_ext.cxx
Looks like a small bug/typo. I'm not sure how it should look, but it works.
> fix building panda

- .github/workflows/mypy.yml
- direct/src/distributed/DistributedObjectAI.py
- direct/src/distributed/DistributedObjectUD.py
- direct/src/task/Task.py
- mypy.ini
This action was pretty outdated. I thought it would be a good idea to update it before working on more type annotations.
> tests: Update mypy to version 1.14.1

- README.md
> Improve bug reporting section in README with links
